/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VazSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "titleMenu": string;
    }
    interface VazTooltip {
        "opened": boolean;
        "text": string;
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLVazSideDrawerElement extends Components.VazSideDrawer, HTMLStencilElement {
    }
    var HTMLVazSideDrawerElement: {
        prototype: HTMLVazSideDrawerElement;
        new (): HTMLVazSideDrawerElement;
    };
    interface HTMLVazTooltipElement extends Components.VazTooltip, HTMLStencilElement {
    }
    var HTMLVazTooltipElement: {
        prototype: HTMLVazTooltipElement;
        new (): HTMLVazTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "vaz-side-drawer": HTMLVazSideDrawerElement;
        "vaz-tooltip": HTMLVazTooltipElement;
    }
}
declare namespace LocalJSX {
    interface VazSideDrawer {
        "opened"?: boolean;
        "titleMenu"?: string;
    }
    interface VazTooltip {
        "opened"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "vaz-side-drawer": VazSideDrawer;
        "vaz-tooltip": VazTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vaz-side-drawer": LocalJSX.VazSideDrawer & JSXBase.HTMLAttributes<HTMLVazSideDrawerElement>;
            "vaz-tooltip": LocalJSX.VazTooltip & JSXBase.HTMLAttributes<HTMLVazTooltipElement>;
        }
    }
}
