/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VazSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "titleMenu": string;
    }
    interface VazSpinner {
    }
    interface VazStockFinder {
    }
    interface VazStockPrice {
        "stockSymbol": string;
    }
    interface VazTooltip {
        "opened": boolean;
        "text": string;
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLVazSideDrawerElement extends Components.VazSideDrawer, HTMLStencilElement {
    }
    var HTMLVazSideDrawerElement: {
        prototype: HTMLVazSideDrawerElement;
        new (): HTMLVazSideDrawerElement;
    };
    interface HTMLVazSpinnerElement extends Components.VazSpinner, HTMLStencilElement {
    }
    var HTMLVazSpinnerElement: {
        prototype: HTMLVazSpinnerElement;
        new (): HTMLVazSpinnerElement;
    };
    interface HTMLVazStockFinderElement extends Components.VazStockFinder, HTMLStencilElement {
    }
    var HTMLVazStockFinderElement: {
        prototype: HTMLVazStockFinderElement;
        new (): HTMLVazStockFinderElement;
    };
    interface HTMLVazStockPriceElement extends Components.VazStockPrice, HTMLStencilElement {
    }
    var HTMLVazStockPriceElement: {
        prototype: HTMLVazStockPriceElement;
        new (): HTMLVazStockPriceElement;
    };
    interface HTMLVazTooltipElement extends Components.VazTooltip, HTMLStencilElement {
    }
    var HTMLVazTooltipElement: {
        prototype: HTMLVazTooltipElement;
        new (): HTMLVazTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "vaz-side-drawer": HTMLVazSideDrawerElement;
        "vaz-spinner": HTMLVazSpinnerElement;
        "vaz-stock-finder": HTMLVazStockFinderElement;
        "vaz-stock-price": HTMLVazStockPriceElement;
        "vaz-tooltip": HTMLVazTooltipElement;
    }
}
declare namespace LocalJSX {
    interface VazSideDrawer {
        "opened"?: boolean;
        "titleMenu"?: string;
    }
    interface VazSpinner {
    }
    interface VazStockFinder {
        "onVazSymbolSelect"?: (event: CustomEvent<string>) => void;
    }
    interface VazStockPrice {
        "stockSymbol"?: string;
    }
    interface VazTooltip {
        "opened"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "vaz-side-drawer": VazSideDrawer;
        "vaz-spinner": VazSpinner;
        "vaz-stock-finder": VazStockFinder;
        "vaz-stock-price": VazStockPrice;
        "vaz-tooltip": VazTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vaz-side-drawer": LocalJSX.VazSideDrawer & JSXBase.HTMLAttributes<HTMLVazSideDrawerElement>;
            "vaz-spinner": LocalJSX.VazSpinner & JSXBase.HTMLAttributes<HTMLVazSpinnerElement>;
            "vaz-stock-finder": LocalJSX.VazStockFinder & JSXBase.HTMLAttributes<HTMLVazStockFinderElement>;
            "vaz-stock-price": LocalJSX.VazStockPrice & JSXBase.HTMLAttributes<HTMLVazStockPriceElement>;
            "vaz-tooltip": LocalJSX.VazTooltip & JSXBase.HTMLAttributes<HTMLVazTooltipElement>;
        }
    }
}
